src/blog/urls.py
from django.urls import path

from blog.views import(

    create_post_view,
    detail_post_view,
    edit_post_view,
    delete_post_view,
    edit_comment_post_view,
    delete_comment_view,

)

app_name = 'blog'

urlpatterns = [
    path('create/', create_post_view, name = "create" ),
    path('<slug>/', detail_post_view, name = "detail" ),
    path('<slug>/edit', edit_post_view, name = "edit" ),
    path('<slug>/delete', delete_post_view, name = "delete" ),
    path('<slug>/edit_comment/<int:comment_id>/',edit_comment_post_view, name='edit_comment'),
    path('<slug>/delete_post_comment/<int:comment_id>/', delete_comment_view, name='delete_comment'),

]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from personal.views import (
    home_screen_view,)

from account.views import(
    registration_view,
    logout_view,
    login_view,
    account_view,
    delete_account_view,
    must_authenticate_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name = "home"),
    path('register/', registration_view, name = "register"),
    path('logout/', logout_view, name = "logout"),
    path('login/', login_view, name = "login"),
    path('account/', account_view, name = "account"),
    path('delete_account/', delete_account_view, name = "delete_account"),
    path('blog/', include('blog.urls', 'blog')),
    path('must_authenticate/', must_authenticate_view, name = "must_authenticate.html"),

    #Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    
    path('password_change/done/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

src/personal/models.py
from django.db import models

# Create your models here.

src/personal/views.py
from django.shortcuts import render
from blog.models import BlogPost
from django.conf import settings
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator
from operator import attrgetter
# Create your views here.

def home_screen_view(request):

    context = {}
    
    blog_posts = sorted(BlogPost.objects.all(), key=attrgetter('date_updated'), reverse=True)
    context['blog_posts'] = blog_posts

    page = request.GET.get("page",1)
    blog_posts_paginator = Paginator(blog_posts, settings.BLOG_POST_PER_PAGE)

    try:
        blog_posts = blog_posts_paginator.page(page)
    except PageNotAnInteger:
        blog_posts = blog_posts_paginator.page(settings.BLOG_POST_PER_PAGE)
    except EmptyPage:
        blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

    context['blog_posts'] = blog_posts 


    return render(request, "personal/home.html", context)

src/personal/templates/personal/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<title>Site de Receitas</title>

<div class="container ">
    <div class="row">

        
        <div class="d-lg-none col-lg-7 offset-lg-1 flex-column text-bg-dark"> 
            <div class="card create-post-bar d-flex flex-column p-3">
				<img class="img-fluid d-block m-auto pb-2" src="{% static 'Logo-site-Blog-com-receitas3SF-removebg-preview.png' %}" width="72" height="72">
				<h3 class="text-center">Publique a sua receita!</h3>
                <p>Compartilhe sua receita favorita com a comunidade.</p>
				<p class="m-auto"><a class="btn btn-warning" href="{% url 'blog:create' %}">Create post</a></p>
			</div>
        </div>
        

        <!-- Blog feed -->
        <div class= "left-column col-lg-7 offset-lg-1 ">
            {% for post in blog_posts %}
            <div class="blog-post-container mt-3">
                {% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
            </div>
            {% empty %}
            <p>Sem Posts</p>
            {% endfor %}

            
        </div>
        
        <!-- End Blog feed -->
        

        <div class="right-column col-lg-3 d-lg-flex d-none flex-column mt-3">
			<div class="card create-post-bar d-flex flex-column p-3 text-bg-dark">
				<img class="img-fluid d-block m-auto pb-2" src="{% static 'Logo-site-Blog-com-receitas3SF-removebg-preview.png' %}" width="72" height="72">
				<h3 class="text-center">Publique a sua receita!</h3>
                <p>Compartilhe sua receita favorita com a comunidade.</p>
				<p class="m-auto"><a class="btn btn-warning" href="{% url 'blog:create' %}">Create post</a></p>
			</div>
		</div>

        {% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts %}
        
    </div>
</div>

{% endblock content %}