src/blog/urls.py
from django.urls import path

from blog.views import(

    create_post_view,
    detail_post_view,
    edit_post_view,
    delete_post_view,
    edit_comment_post_view,
    delete_comment_view,

)

app_name = 'blog'

urlpatterns = [
    path('create/', create_post_view, name = "create" ),
    path('<slug>/', detail_post_view, name = "detail" ),
    path('<slug>/edit', edit_post_view, name = "edit" ),
    path('<slug>/delete', delete_post_view, name = "delete" ),
    path('<slug>/edit_comment/<int:comment_id>/',edit_comment_post_view, name='edit_comment'),
    path('<slug>/delete_post_comment/<int:comment_id>/', delete_comment_view, name='delete_comment'),

]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from personal.views import (
    home_screen_view,)

from account.views import(
    registration_view,
    logout_view,
    login_view,
    account_view,
    delete_account_view,
    must_authenticate_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name = "home"),
    path('register/', registration_view, name = "register"),
    path('logout/', logout_view, name = "logout"),
    path('login/', login_view, name = "login"),
    path('account/', account_view, name = "account"),
    path('delete_account/', delete_account_view, name = "delete_account"),
    path('blog/', include('blog.urls', 'blog')),
    path('must_authenticate/', must_authenticate_view, name = "must_authenticate.html"),

    #Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    
    path('password_change/done/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver
from random import randint
# Create your models here.

SLUG_LIST = []

def upload_location(instance,filename):
    
    file_path = 'blog/{author_id}/{title}-{filename}'.format(
        author_id=str(instance.author.id), title = str(instance.title), filename = filename
        )
    
    return file_path


class BlogPost(models.Model):

    title = models.CharField(max_length=50, null=False, blank=False)
    body = models.TextField(max_length=5000, null=False, blank=False)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    date_updated = models.DateTimeField(auto_now=True, verbose_name="date updated")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title
    
    
class Rating(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.post.title}: {self.rating}"
    
        
@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance,**kwargs):
    instance.image.delete(False)

def pre_save_blog_post_receiever(sender,instance, *args, **kwargs):

    if not instance.slug:
        slug_random = 0
        while slug_random not in SLUG_LIST:
            slug_random = randint(0,1000)
            SLUG_LIST.append(slug_random)
            
        instance.slug = slugify(instance.author.username + "-" + str(slug_random))
        

pre_save.connect(pre_save_blog_post_receiever, sender=BlogPost)


class CommentBlogPost(models.Model):

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(BlogPost, related_name="comments", on_delete=models.CASCADE)
    body = models.TextField(max_length=500, null=False, blank=False)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    date_updated = models.DateTimeField(auto_now=True, verbose_name="date updated")
   
    def __str__(self):
        return self.body
    

src/blog/forms.py
from django import forms

from blog.models import BlogPost, CommentBlogPost

class CreateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']

class UpdateBlogPostFrom(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']

        def save(self,commit = True):
            blog_post = self.instance
            blog_post.title = self.cleaned_data['title']
            blog_post.body = self.cleaned_data['body']
            
            if self.cleaned_fata['image']:
                blog_post.image = self.cleaned_data['image']

            if commit:
                blog_post.save()
                
            return blog_post

class CommentBlogPostForm(forms.ModelForm):

    class Meta:
        model = CommentBlogPost
        fields = ['body']


class UpdateCommentBlogPostForm(forms.ModelForm):

    class Meta:
        model = CommentBlogPost
        fields = ['body']

        def save(self,commit = True):
            blog_post_comment = self.instance
            blog_post_comment.body = self.cleaned_data['body']

            if commit:
                blog_post_comment.save()
                
            return blog_post_comment

src/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404

from blog.forms import CreateBlogPostForm,UpdateBlogPostFrom, CommentBlogPostForm, UpdateCommentBlogPostForm
from account.models import Account
from django.contrib import messages
from blog.models import BlogPost, CommentBlogPost



# Create your views here.

def create_post_view(request):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate.html')

    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = CreateBlogPostForm()
        messages.success(request, 'Post feito com sucesso!') 
        return redirect('home')

    context['form'] = form

    return render(request,"blog/create_post.html",{})

def delete_post_view(request, slug):
    context = {}
    blog_post = get_object_or_404(BlogPost, slug=slug)

    if request.POST:
        blog_post.image.delete()
        blog_post.delete()
        messages.success(request, 'Post excluído com sucesso!')
        return redirect('home')

    
    context['blog_post'] = blog_post

    return render(request, 'blog/delete_post.html', context)


def detail_post_view(request, slug):

    context = {}

    blog_post = get_object_or_404(BlogPost, slug=slug)
    context['blog_post'] = blog_post
    
    
    if request.POST:
         
        user = request.user
        if not user.is_authenticated: 
            return redirect('must_authenticate.html')
    
        form = CommentBlogPostForm(request.POST)
        
        if form.is_valid():
            
            comment = form.save(commit=False)
            comment.author = request.user  
            comment.post = blog_post  
            comment.save()
            form = CommentBlogPostForm()  

    else:
        form = CommentBlogPostForm()

    comments = CommentBlogPost.objects.filter(post=blog_post)

    context['form'] = form
    context['comments'] = comments

    return render(request, 'blog/detail_post.html', context)

def edit_post_view(request,slug):

    context = {}

    user = request.user
    if not user.is_authenticated: 
        return redirect('must_authenticate.html')
    
    blog_post = get_object_or_404(BlogPost,slug = slug)

    if blog_post.author != user:
        return redirect("home")

    if request.POST:
        form = UpdateBlogPostFrom(request.POST or None, request.FILES or None, instance=blog_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()  
            messages.success(request, 'Post atualizado com sucesso!') 
            blog_post = obj
            return redirect('home')

    form = UpdateBlogPostFrom(
        initial= {
                "title": blog_post.title,
                "body": blog_post.body,
                "image": blog_post.image,
        }
    )

    context['form'] = form
    return render(request, 'blog/edit_post.html', context)


def edit_comment_post_view(request, slug, comment_id ):

    context = {}

    comment = get_object_or_404(CommentBlogPost, id=comment_id)
    blog_post = get_object_or_404(BlogPost, slug=slug)
    context['blog_post'] = blog_post
    
    
    if request.user != comment.author:
        return redirect('blog:detail', slug=comment.post.slug)

    if request.POST:
        form = UpdateCommentBlogPostForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('blog:detail', slug=comment.post.slug)  
    

    form = UpdateBlogPostFrom(
        initial= {
                "body": comment.body,    
        }
    )

    context['form'] = form
    context['blog_post_comment'] = comment

    return render(request, 'blog/edit_comment.html', context)


def delete_comment_view(request, slug, comment_id):

    context = {}

    comment = get_object_or_404(CommentBlogPost, id=comment_id)

    if request.POST:
       
        comment.delete()
        messages.success(request, 'Comentário excluído com sucesso!')
        return redirect('blog:detail', slug=comment.post.slug)  
        
    context['blog_post_comment'] = comment       

    return render(request, 'blog/delete_post_comment.html', context)

src/blog/templates/blog/create_post.html
{% extends 'base.html' %}

{% block content %}

<title>Criar um Post</title>

<div class="container mt-5 ">
    <div class="row justify-content-center ">
        <div class="col-md-6 ">
            <div class="card text-bg-dark">
                <div class="card-header ">
                    <h3 class="text-center">Criar Nova Postagem</h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_title" class="form-label">Título</label>
                            <input type="text" name="title" class="form-control text-bg-dark" id="id_title" placeholder="Título" required autofocus>
                        </div>
                        <div class="mb-3">
                            <label for="id_body" class="form-label">Conteúdo</label>
                            <textarea name="body" id="id_body" rows="10" class="form-control text-bg-dark" placeholder="Qual é a sua receita?" required></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="id_image" class="form-label text-bg-dark">Imagem</label>
                            <input type="file" name="image" id="id_image" accept="image/*" class="form-control text-bg-dark">
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-warning">POSTAR</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

src/blog/templates/blog/delete_post.html
{% extends 'base.html' %}

{% block content %}

<title>Deletar {{blog_post.title}}</title>

<div class="container">
    <div class="row">
        
        <!-- Blog post -->
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card m-auto mt-4" style="width: 900px;">
                <div class="card-body my-2">
                    <h3 class="text-center">Tem certeza que deseja deletar o post?</h3>
                    <hr>
                    {% if blog_post.author == request.user %}
                    <p class="card-text"> Postado por Você, em {{blog_post.date_published}} </p>
                    {% else %}
                    <p class="card-text"> Postado por {{blog_post.author}}, em {{blog_post.date_published}} </p>
                    {% endif %}
                    <div class="d-flex justify-content-between align-items-center"> 
                        <h2 class="card-title">{{blog_post.title}}</h2>
                    </div>
                    <hr>
                    <div class="container">
                        <p class="card-text">{{blog_post.body|safe}}</p>
                    </div>
                    {% if blog_post.image %}
                        <hr>
                        <img class="card-img-top" src="{{blog_post.image.url}}" alt="">
                    {% endif %}
            
                    <div class="mt-3 text-center">
                        <button type="submit" class="btn btn-danger">Deletar Post</button> 
                    </div>
                </div>
                <div class="card-footer text-muted">
                    Atualizado em {{blog_post.date_updated}} por {{blog_post.author}}
                </div>
                
            </div>
        </form>
        <!-- END Blog post -->

    </div>
</div>

{% endblock content%}

src/blog/templates/blog/delete_post_comment.html
{% extends 'base.html' %}

{% block content %}

<title>Deletar {{blog_post.title}}</title>

<div class="container">
    <div class="row">
        
        <!-- Blog post -->
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card m-auto mt-4" style="width: 900px;">
                <div class="card-body my-2">
                    <h3 class="text-center">Tem certeza que deseja deletar o Cometário?</h3>
                    <hr>
                    <p class="card-text"> Postado por Você, em {{blog_post_comment.date_updated}} </p>
                    <div class="d-flex justify-content-between align-items-center"> 
                        <h2 class="card-title">{{blog_post_comment.title}}</h2>
                    </div>
                    <hr>
                    <div class="container">
                        <p class="card-text">{{blog_post_comment.body|safe}}</p>
                    </div>
                    <hr>
                    <div class="mt-3 text-center">
                        <button type="submit" class="btn btn-danger">Deletar Post</button> 
                    </div>
                </div>
                <div class="card-footer text-muted">
                    Atualizado em {{blog_post_comment.date_updated}} por {{blog_post_comment.author}}
                </div>
                
            </div>
        </form>
        <!-- END Blog post -->

    </div>
</div>

{% endblock content%}

src/blog/templates/blog/detail_post.html
{% extends 'base.html' %}

{% block content %}
    
    <title>{{ blog_post.title }}</title>

    <div class="container">
        <div class="row">
            <!-- Blog post -->
            <div class="card m-auto mt-4 text-bg-dark" style="width: 900px;">
                <div class="card-body my-2">
                    {% if blog_post.author == request.user %}
                    <p class="card-text">Postado por Você, em {{ blog_post.date_published }}</p>
                    {% else %}
                    <p class="card-text">Postado por {{ blog_post.author }}, em {{ blog_post.date_published }}</p>
                    {% endif %}
                    <div class="d-flex justify-content-between align-items-center"> 
                        <h2 class="card-title">{{ blog_post.title }}</h2>
                        {% if blog_post.author == request.user %}
                        <div class="d-flex justify-content-end mx-2">
                            <a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-warning mx-2">Editar Post</a>
                            <a href="{% url 'blog:delete' blog_post.slug %}" class="btn btn-danger">Deletar Post</a>
                        </div> 
                        {% endif %}
                    </div>
                    <hr>
                    <div class="container">
                        <pre class="card-text">{{ blog_post.body|safe }}</pre>
                    </div>
                    {% if blog_post.image %}
                    <hr>
                    <img class="card-img-top" src="{{ blog_post.image.url }}" alt="">
                    {% endif %}
                </div>
                <div class="card-footer text-muted">
                    Atualizado em {{ blog_post.date_updated }} por {{ blog_post.author }}
                </div>
                
                <!-- Comentários -->
                
                <div class="card mt-3 text-bg-dark">
                    <div class="card-body">
                        <h3>Comentários</h3>
                        <hr>
                        {% for comment in blog_post.comments.all %}
                        <div class="comment text">
                            <div class="d-flex justify-content-between">
                                <strong>{{ comment.author }}</strong>
                                {% if comment.date_published == comment.date_updated %}
                                <span>{{ comment.date_published }}</span>
                                {% else %}
                                <span>Att. {{ comment.date_updated }}</span>
                                {% endif %}
                            </div>
                            <p>{{ comment.body }}</p>

                            <!-- Botão de Edição de Comentário -->
                            
                            {% if comment.author == request.user %}
                                <a href="{% url 'blog:edit_comment' blog_post.slug comment.id %}" class="btn btn-warning ">Editar Comentário</a>
                            {% endif %}
                        </div>
                        <hr>
                        {% empty %}
                        <p>Nenhum comentário ainda.</p>
                        {% endfor %}
                    </div>
                </div>
                <!-- Fim dos Comentários -->


                <!-- Formulário para adicionar um novo comentário -->
                <div class="card mt-3 text-bg-dark">
                    <div class="card-body">
                        <h3>Adicione um Comentário</h3>
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group ">
                                <label for="id_body" class="form-label">Comentário</label>
                                <textarea name="body" id="id_body" rows="3" class="form-control text-bg-dark" placeholder="Qual é a o seu comentário" required></textarea>
                            </div>
                            <button type="submit" class="btn btn-warning mt-3 ">Enviar Comentário</button>
                        </form>
                    </div>
                </div>
                <!-- Fim do Formulário de Comentário -->
                <p></p>
            </div>
            <!-- END Blog post -->
            
        </div>
    </div>
{% endblock content %}

src/blog/templates/blog/edit_comment.html
{% extends 'base.html' %}

{% block content %}

<title>Editar {{blog_post.title}}</title>

<div class="container mt-2">
    <div class="row justify-content-center">
        <div class="align-items-center">
            <div class="card m-auto mt-4" style="width: 900px;">
                <div class="card-header">
                    <h3 class="text-center">Editar Comentario</h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3 form-group">
                            <label for="id_body" class="form-label">Conteúdo</label>
                            <textarea name="body" id="id_body" rows="10" class="form-control" placeholder="Qual é a sua receita?" required>{{form.initial.body}} </textarea>
                        </div>

                        {% for field in form %}
                            <p>
                                {% for error in field.errors %}
                                    <span style="color: red;">{{ error }}</span>
                                {% endfor %}
                            </p>
                        {% endfor %}

                        {% if form.non_field_errors %}
                            <div style="color: red;">
                                <p>{{ form.non_field_errors }}</p>
                            </div>
                        {% endif %} 

                        <div class="mt-3 d-flex justify-content-between">
                            <button type="submit" class="btn btn-warning">Atualizar Comentário</button> 
                            <a href="{% url 'blog:delete_comment' blog_post.slug blog_post_comment.id %}"  type="button" class="btn btn-danger">Deletar Comentário</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    
</script>


{% endblock content %}

src/blog/templates/blog/edit_post.html
{% extends 'base.html' %}

{% block content %}

<title>Editar {{blog_post.title}}</title>

<div class="container mt-2">
    <div class="row justify-content-center">
        <div class="align-items-center">
            <div class="card m-auto mt-4" style="width: 900px;">
                <div class="card-header">
                    <h3 class="text-center">Editar Postagem</h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3 form-group">
                            <label for="id_title" class="form-label">Título</label>
                            <input type="text" name="title" class="form-control" id="id_title" placeholder="Título" value="{{form.initial.title}}" autofocus>
                        </div>
                        <div class="mb-3 form-group">
                            <label for="id_body" class="form-label">Conteúdo</label>
                            <textarea name="body" id="id_body" rows="10" class="form-control" placeholder="Qual é a sua receita?" required>{{form.initial.body}} </textarea>
                        </div>
                        <div class="mb-3">
                            {% if form.initial.image %}
                            <img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
                            {% endif %}
                            <label for="id_image" class="form-label mt-3">Nova Imagem</label>
                            <input type="file" name="image" id="id_image" accept="image/*" class="form-control">
                        </div>

                        {% for field in form %}
                            <p>
                                {% for error in field.errors %}
                                    <span style="color: red;">{{ error }}</span>
                                {% endfor %}
                            </p>
                        {% endfor %}

                        {% if form.non_field_errors %}
                            <div style="color: red;">
                                <p>{{ form.non_field_errors }}</p>
                            </div>
                        {% endif %} 
                        <div class="mt-3 d-flex justify-content-between">
                            <button type="submit" class="btn btn-primary">Atualizar Post</button> 
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    
</script>


{% endblock content %}